Name:       findutils
Summary:    The GNU versions of find utilities (find and xargs)
Version:    4.2.31
Release:    2
Group:      Applications/File
License:    GPLv2+
URL:        http://www.gnu.org/software/findutils/
Source0:    ftp://ftp.gnu.org/gnu/findutils/%{name}-%{version}.tar.gz
Patch0:     findutils-4.2.31-no-locate.patch
Patch1:     findutils-bmc12931-find-ls-stack-overflow.patch
Patch2:     findutils-aarch64.patch
BuildRequires:  libtool
BuildRequires:  automake
BuildRequires:  autoconf
BuildRequires:  gzip
BuildRequires:  gettext-devel
BuildRequires:  texinfo

%description
The findutils package contains programs which will help you locate
files on your system.  The find utility searches through a hierarchy
of directories looking for files which match a certain set of criteria
(such as a filename pattern).  The xargs utility builds and executes
command lines from standard input arguments (usually lists of file
names generated by the find command).

You should install findutils because it includes tools that are very
useful for finding things on your system.

%package doc
Summary:    Documentation for %{name}
Group:      Documentation
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/install-info
Requires(postun): /sbin/install-info

%description doc
Man and info pages for %{name}.

%prep
%setup -q -n %{name}-%{version}

# findutils-4.2.31-no-locate.patch
%patch0 -p1
# findutils-bmc12931-find-ls-stack-overflow.patch
%patch1 -p1
%patch2 -p1

%build
export CFLAGS="$RPM_OPT_FLAGS -D_GNU_SOURCE"
export CXXFLAGS="$RPM_OPT_FLAGS -D_GNU_SOURCE"

%configure --disable-static \
    --without-selinux

make %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

rm -f $RPM_BUILD_ROOT%{_infodir}/dir

mkdir -p %{buildroot}/bin
pushd %{buildroot}/bin
ln -sf ../usr/bin/find
popd
%find_lang %{name}

mkdir -p %{buildroot}%{_docdir}/%{name}-%{version}
install -m0644 -t %{buildroot}%{_docdir}/%{name}-%{version} \
        AUTHORS NEWS README THANKS TODO

%post doc
%install_info --info-dir=%_infodir %{_infodir}/find.info.gz

%postun doc
if [ $1 = 0 ] ;then
%install_info_delete --info-dir=%{_infodir} %{_infodir}/find.info.gz
fi

%files -f %{name}.lang
%defattr(-,root,root,-)
%license COPYING
%{_bindir}/find
/bin/find
%{_bindir}/xargs

%files doc
%defattr(-,root,root,-)
%{_mandir}/man1/find.1*
%{_mandir}/man1/xargs.1*
%{_infodir}/find.info.gz
%{_docdir}/%{name}-%{version}
